services:
  _defaults:
    autowire: true
    autoconfigure: true

  PhpGuild\DoctrineExtraBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources,DoctrineExtraBundle.php}'

  PhpGuild\DoctrineExtraBundle\EventSubscriber\DoctrineClassMetadata\:
    resource: ../../EventSubscriber/DoctrineClassMetadata
    tags:
      - { name: doctrine.event_subscriber, priority: 256 }
