services:
  _defaults:
    autowire: true
    autoconfigure: true

  PhpGuild\DoctrineExtraBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources,DoctrineExtraBundle.php}'

  PhpGuild\DoctrineExtraBundle\EventSubscriber\UuidSubscriber:
    tags:
      - { name: 'doctrine.event_subscriber' }
