services:
  _defaults:
    autowire: true
    autoconfigure: true

  PhpGuild\DoctrineExtraBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources,DoctrineExtraBundle.php}'

  PhpGuild\DoctrineExtraBundle\EventSubscriber\UuidMetadataSubscriber:
    tags:
      - { name: doctrine.event_subscriber, priority: 256 }

  PhpGuild\DoctrineExtraBundle\EventSubscriber\EnabledMetadataSubscriber:
    tags:
      - { name: doctrine.event_subscriber, priority: 256 }
